name: Build EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
        pip install --user -r requirements.txt  # 关键修复：添加 --user
        pip install --user pylibjpeg pylibjpeg-openjpeg  # 明确安装
        pip install --user pyinstaller
    - name: Build EXE
      run: |
          pyinstaller --onefile --hidden-import pydicom.uid --collect-data pydicom main.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: exe-file
        path: dist/